spring:
  application:
    name: main-application

proxy:
  chat-bot:
    url: http://localhost/v1/8000



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082